name: DevOps Auto Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Run basic test
      run: |
        cd backend
        node -e "console.log('App build successful')"